//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        public int ID { get; set; }
        public string Producer { get; set; }
        public int Core { get; set; }
        public int Frequency { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
